version: '2'
services:
  dev_nginx_web:
    #restart: always
    image: nginx:latest
    ports:
      - "${PHP_PORT}:80"
    links:
      - dev_php:phpfpm
    volumes:
      - .:/code
      - ./dev_env/nginx_default.conf:/etc/nginx/conf.d/default.conf
      - ./dev_env/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - dev_php
      - dev_mysql_db
  dev_php:
    build:
      context: .
      dockerfile: ./dev_env/Dockerfile_php
    volumes:
      - .:/code
    working_dir: /code

  dev_mysql_db:
    #restart: always
    image: mysql:5.7
    ports:
      - "${DB_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootPassword!
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
